Import('*')
Install(env, Split("""
    COPYRIGHT.TXT
    Vera.ttf
    VeraBI.ttf
    VeraBd.ttf
    VeraIt.ttf
    VeraMoBI.ttf
    VeraMoBd.ttf
    VeraMoIt.ttf
    VeraMono.ttf
    VeraSe.ttf
    VeraSeBd.ttf
"""))
