Import('base_env TOOLS')

SOURCES = [
    'ListenerThread.cpp',
    'Main.cpp',
    'Server.cpp',
    'ServerFrame.cpp',
    'World.cpp']

env = base_env.Copy()
for t in Split('PyrBase NSPR wxWindows'):
    TOOLS[t](env)

env.Program('#/build/server', SOURCES)
