Import('env TOOLS')

SOURCES = Split("""
    Account.cpp
    Character.cpp
    Configuration.cpp
    ConnectionHolder.cpp
    Database.cpp
    Game.cpp
    ListenerThread.cpp
    LogEvent.cpp
    Main.cpp
    Server.cpp
    ServerApp.cpp
    ServerAppearance.cpp
    ServerEntity.cpp
    ServerFrame.cpp
    ServerLog.cpp
    ServerThread.cpp
""")

env = env.Copy()
for t in Split('PyrBase Expat NSPR Corona wxWindows'):
    TOOLS[t](env)

server = env.Program('#/build/server', SOURCES)
Alias('server', server)
