from os.path import join
from glob import glob

TARGET = ARGUMENTS.get('TARGET', '.')
Default(TARGET)

DIRS = Split("""
   images
""")

WILD = Split("""
   *.png
   *.jpg
   *.jpeg
""")

env = Environment()

for d in DIRS:
    for w in WILD:
        files = glob("%s/%s" % (d, w))
        env.Install(join(TARGET, d), files)
