Import('*')

Install(env, Split("""
    backdrop.jpg
    menu.png
    particle.png
    pointer.png
    MikeThumbnail.jpg
    CaphrielFace.jpg
    robot_screen.jpg
"""))

ConvertImage(env, 'intro.tga', 'intro.png')
ConvertImage(env, 'stars.tga', 'stars.png')
ConvertImage(env, 'title/title_composite.tga', 'title/title_composite.png')
