Import('env TOOLS')

SOURCES = Split("""
    BoxLayout.cpp
    Button.cpp
    CheckBox.cpp
    Insets.cpp
    Label.cpp
    ListBox.cpp
    MessageBox.cpp
    Picture.cpp
    Rect.cpp
    RootWidget.cpp
    SDLBridge.cpp
    Size.cpp
    TextField.cpp
    Version.cpp
    Widget.cpp
    Window.cpp
""")

env = env.Copy()
for t in ['PyrBase', 'SDL', 'NSPR', 'GLText']:
    TOOLS[t](env)
env.Library('phui', SOURCES)
