Import('*')

SOURCES = Split("""
    BoxLayout.cpp
    Button.cpp
    CheckBox.cpp
    Insets.cpp
    Label.cpp
    ListBox.cpp
    MessageBox.cpp
    Picture.cpp
    Rect.cpp
    RootWidget.cpp
    SDLBridge.cpp
    Size.cpp
    TextField.cpp
    Version.cpp
    Widget.cpp
    Window.cpp
""")

env = env.Copy(tools=['pyr_base', 'sdl', 'nspr', 'gltext'])
env.Library('phui', SOURCES)
