Import('base_env')
Import('SetupCal3D SetupCorona SetupFreeType SetupNSPR SetupSDL SetupGL')

SOURCES = [
    'Application.cpp',
    'Font.cpp',
    'GameState.cpp',
    'InputManager.cpp',
    'IntroState.cpp',
    'Main.cpp',
    'MenuState.cpp',
    'Model.cpp',
    'ParticleEmitter.cpp',
    'ParticleSystem.cpp',
    'PlayerEntity.cpp',
    'Profiler.cpp',
    'Renderer.cpp',
    'ResourceManager.cpp',
    'Scene.cpp',
    'SDLUtility.cpp',
    'ServerConnection.cpp',
    'Texture.cpp',
    'extgl.c']

env = base_env.Copy()
SetupCal3D(env)
SetupCorona(env)
SetupFreeType(env)
SetupNSPR(env)
SetupSDL(env)
SetupGL(env)

env['LIBS'] += ['base']

env.Program('#/build/client', SOURCES)
