Import('base_env TOOLS')

SOURCES = Split("""
    AppearanceFactory.cpp
    Application.cpp
    Configuration.cpp
    CreditsState.cpp
    GameEntity.cpp
    GameState.cpp
    HUD.cpp
    InputManager.cpp
    IntroState.cpp
    Main.cpp
    MenuState.cpp
    Model.cpp
    ParticleEmitter.cpp
    ParticleSystem.cpp
    Profiler.cpp
    Renderer.cpp
    Scene.cpp
    SDLUtility.cpp
    ServerConnection.cpp
    ServerConnectionThread.cpp
""")

env = base_env.Copy()
for t in Split('PyrBase PHUI Cal3D Corona Expat GLText NSPR OpenGL SDL'):
    TOOLS[t](env)

client = env.Program('#/build/client', SOURCES)
Alias('client', client)
