Import('base_env SetupSDL SetupGL')

SOURCES = [
    'Application.cpp',
    'Font.cpp',
    'GameState.cpp',
    'InputManager.cpp',
    'IntroState.cpp',
    'Main.cpp',
    'MenuState.cpp',
    'Model.cpp',
    'ParticleEmitter.cpp',
    'ParticleSystem.cpp',
    'PlayerEntity.cpp',
    'Profiler.cpp',
    'Renderer.cpp',
    'ResourceManager.cpp',
    'SDLUtility.cpp',
    'ServerConnection.cpp',
    'Texture.cpp',
    'extgl.c']

env = base_env.Copy()
SetupSDL(env)
SetupGL(env)

env['LIBPATH'] += ['../base']
env['LIBS'] += ['base','nspr4']

env.Program('#/build/client.exe', SOURCES)
