Import('*')
env = env.Copy(tools=['pyr_base', 'nspr', 'expat'])

tests = ['testCallStack.cpp',
         'testCondVar.cpp',
         'testLog.cpp',
         'testThreads.cpp',
         'packetClient.cpp',
         'packetServer.cpp']

[env.Program(t) for t in tests]
