Import('*')
env = env.Copy(tools=['pyr_base', 'nspr', 'expat'],
               toolpath=[Dir('#/toolspec').abspath])

env.Program('testCallStack.cpp')
env.Program('testLog.cpp')
env.Program('packetServer.cpp')
env.Program('packetClient.cpp')
