Import('base_env TOOLS')

SOURCES = [
    'ByteBuffer.cpp',
    'Canvas.cpp',
    'Connection.cpp',
    'Error.cpp',
    'LoginPacket.cpp',
    'Map.cpp',
    'NSPRUtility.cpp',
    'PacketFactory.cpp',
    'ReaderThread.cpp',
    'ServerSocket.cpp',
    'Socket.cpp',
    'Thread.cpp',
    'Utility.cpp',
    'WriterThread.cpp']

env = base_env.Copy()
TOOLS['NSPR'](env)

env.Library('base', SOURCES)
