Import('base_env TOOLS')

SOURCES = Split("""
    ByteBuffer.cpp
    Canvas.cpp
    Connection.cpp
    Error.cpp
    MapElement.cpp
    MapFile.cpp
    MapRenderer.cpp
    NSPRUtility.cpp
    PacketFactory.cpp
    PacketTypes.cpp
    Platform.cpp
    ReaderThread.cpp
    ResourceManager.cpp
    ServerSocket.cpp
    Socket.cpp
    Texture.cpp
    Thread.cpp
    Utility.cpp
    WriterThread.cpp
    XMLParser.cpp
""")

if base_env['USE_EXTGL']:
    SOURCES.append('extgl.c')

env = base_env.Copy()
TOOLS['NSPR'](env)

env.Library('base', SOURCES)
